name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: tshirts fail
        run: bash .github/workflows/expectfail.sh "node test/tshirtTest.js"

      - name: misaligned fail
        run: bash .github/workflows/expectfail.sh "node test/misalignedTest.js"

      - name: alerter fail
        run: bash .github/workflows/expectfail.sh "node test/alerterTest.js"